export const cities =
{

    "Alexandria": ["Abu Qir", "Abu Talat", "Agami", "Al Hadrah", "Al Ibrahimiyyah", "Amreya", "Asafra", "Attarin", "Awayed", "Azarita", "Bacchus", "Bahray ", " Anfoshy", "Bolkly", "Borg al Arab", "Camp Caesar", "Cleopatra", "Dekheila", "Zahria", "El Max", "Fleming", "Gianaclis", "Glim", "Gomrok", "Kabbary", "Kafr Abdo", "Karmous", "Koum al Dikka", "Labban", "Laurent", "Maamoura", "Mandara", "Manshiyya", "Miami", "Moharam Bik", "Montazah", "Nakheel", "Raml Station", "Ras El Tin", "Roushdy", "Saba Pasha", "Salehia", "San Stefano", "Schutz", "Seyouf", "Shatby", "Sidi Beshr", "Sidi Gaber", "Smoha", "Sporting", "Stanley", "Victoria", "Wardian", "Zezenia"],
    "Beni Suef": ["Al Feshn", "Al Wasty", "Beba", "Beni Suef City", "Ehnasia", "Nasser", "New Beni Suef", "Samasta"],
    "Aswan": ["Abou al Reish", "Abou Simbel", "Aswan City", "Basiliah", "Daraw", "Edfu", "Kalabsha", "Kom Ombo", "Nasr al Noba", "Rdesiah", "Sahara", "Sebaeiah"],
    "Beheira": ["Abou Homs", "Abuu al Matamer", "Damanhour", "Delengat", "Edko", "Etay al Barud", "Hosh Essa", "Kafr al Dawwar", "Kom Hamadah", "Mahmoudiyah", "Markaz Badr", "Nubariyah", "Rahmaniya", "Rashid", "Shubrakhit", "Wadi al Natrun"],
    "Asyut": ["Abnub", "Abu Teeg", "Asyut City", "Badari", "Dairut", "Fateh", "Ghanayem", "Manfalut", "New Assiut", "New Tiba", "Qusiya", "Sahel Selim", "Sedfa"],
    "Dakahlia": ["Aga", "Akhtab", "Bani Ubayd", "Belqas", "Dikirnis", "El Kordy", "Gamasa", "Mansoura", "Manzala", "Markaz El Gamaleya", "Markaz El Matareya", "Minat al Nasr", "Mit Ghamr", "Mit Slseel", "Nabaruh", "New Mansoura", "Shirbin", "Sinbillawain", "Talkha", "Tama al Amdeed", "Damas"],
    "Damietta": ["Damietta City", "Ezbet al Burj", "Fareskour", "Kafr al Bateekh", "Kafr Saad", "Markaz El Rodah", "Mit Abughalb", "New Damietta", "Ras al Bar", "Saro", "Zarqa"],
    "Fayoum": ["Atssa", "Fayoum City", "Ibshway", "New Fayoum", "Sinnuras", "Tamiya", "Yusuf al Sadiq"],
    "Gharbia": ["Basyoun", "Kafr al Zayat", "Mahalla al Kobra", "Qutour", "Samanoud", "Santa", "Tanta", "Zefta"],
    "Ismailia": ["Abu Swear", "Fayed", "Ismailia City", "Kantara East", "Kantara West", "Qassaseen", "Tal al Kebeer"],
    "Kafr al Sheikh": ["Baltim", "Bella", "Brolos", "Desouk", "Fouh", "Hamoul", "Kafr al Sheikh City", "Motobas", "Qaleen", "Riyadh", "Sidi Salem"],
    "Luxor": ["Armant", "Bayadeya", "Isna", "Luxor City", "Qurna", "Tod", "Zinnia"],
    "Matruh": ["Alamein", "Barany", "Dabaa", "Hammam", "Marsa Matrouh", "Nagela", "North Coast", "Salloum", "Siwa"],
    "Minya": ["Abu Qurqas", "Adwa", "Beni Mazar", "Deir Mawas", "Maghagha", "Malawi", "Matay", "Minya City", "New Minya", "Samalut"],
    "Monufia": ["Ashmon", "Bagour", "Berket al Sabaa", "Menouf", "Quesna", "Sadat", "Sers al Lyan", "Shebin al Koum", "Shohadaa", "Tala"],
    "Qalyubia": ["Bahtim", "Banha", "Kafr Shukr", "Khanka", "Khosous", "Musturad", "Qaha", "Qalyub", "Qanater al Khairia", "Shebin al Qanater", "Shubra al Khaimah", "Tookh"],
    "Port Said": ["Arab District", "Dawahy District", "Ganoub District", "Manakh District", "Port Fouad", "Sharq District", "Zohour District"],
    "New Valley": ["Balat", "Dakhla", "Farafra", "Kharga", "Mut", "Paris"],
    "North Sinai": ["Arish", "Bir al Abed", "Hasana", "Nakhl", "Rafah", "Sheikh Zoweyd"],
    "Qena": ["Abu Tisht", "Dishna", "Farshout", "Keft", "Nag Hammadi", "Nakada", "Qena City", "Quos", "Wakf"],
    "Sohag": ["Akhmim", "Alasirat", "Baliana", "Girga", "Maragha", "Markaz Dar El Salam", "Markaz Juhaynah", "Markaz Sohag", "Monsha'a", "New Sohag", "Sakaltah", "Tahta", "Tama"],
    "Red Sea": ["Gouna", "Halayeb Shalateen", "Hurghada", "Marsa Alam", "Qusair", "Ras Gharib", "Safaga", "Sahl Hasheesh"],
    "Sharqia": ["10th of Ramadan", "Abu Hammad", "Abu Kabir", "Alqnayat", "Awlad Saqr", "Bilbeis", "Deyerb Negm", "Faqous", "Hihya", "Husseiniya", "Ibrahemyah", "Kafr Saqr", "Mashtool al Souk", "Minya al Qamh", "New Salhia", "Qareen", "Zagazig"],
    "South Sinai": ["Abu Rudeis", "Abu Zenimah", "Dahab", "Nuweiba", "Ras Sedr", "Sharm al Sheikh", "St. Catherine", "Taba", "Tor Sinai"],
    "Suez": ["Ain Sukhna", "Arbaeen", "Attaka", "Faisal District", "Ganayen", "Suez District"],
    "Cairo": ["10th Ramadan City", "15 May City", "Abasiya", "Ain Shams", "Al Amiriyyah", "Al Manial", "Almazah", "Ataba", "Bab al Shereia", "Badr City", "Basateen", "Boulaq", "Dar al Salaam", "Darb al Ahmar", "Darrasa", "Downtown Cairo", "El Fostat", "Ezbet El Nakhl", "Gamaleya", "Garden City", "Gesr Al Suez", "Hadayek al Kobba", "Hadayek Helwan", "Heliopolis", "Helmeya al Gadeda", "Helmeyat El Zaytoun", "Helwan", "Katameya", "Ma'sara", "Maadi", "Madinaty", "Marg", "Masr al Kadema", "Matareya", "Mokattam", "Moski", "Mostakbal City", "Nasr City", "New Cairo ", " El Tagamoa", "New Capital City", "New Heliopolis", "New Nozha", "Obour City", "Qasr al Nil", "Ramses", "Rehab City", "Rod al Farag", "Salam City", "Sayeda Zeinab", "Sharabeya", "Sheraton", "Shorouk City", "Shubra", "Tebeen", "Tura", "Waili", "Zahraa Al Maadi", "Zamalek", "Zawya al Hamra", "Abdeen", "ELDaher", "Khalifa", "New Maadi"],
    "Giza": ["6th of October", "Abu Rawash", "Agouza", "Ard El Lewa", "Badrasheen", "Baragil", "Bashtil", "Boulaq Dakrour", "Dahab Island and Coldair", "Dahshur", "Dokki", "El Ayyat", "Faisal", "Giza District", "Hadayek 6th of October ", "Hadayek al Ahram", "Haram", "Hawamdeya", "Imbaba", "Kerdasa", "Kit Kat", "Manial Shiha", "Mansuriyya", "Markaz al Giza", "Maryotaya", "Mohandessin", "Moneeb", "Nahia", "Oseem", "Saf", "Saft El Laban", "Sheikh Zayed", "Tersa", "Warraq", "West Somid", "Omrania"],
}